# Generated by Django 4.2.4 on 2023-10-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPasskeyDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True, help_text="Is this device ready for use?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(null=True, verbose_name="last used at"),
                ),
                (
                    "flags",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="flags"
                    ),
                ),
                (
                    "aaguid",
                    models.BinaryField(
                        help_text="The AAGUID of the authenticator. It can be used to identify the make and model of the authenticator but is often zeroed out to protect user privacy.",
                        max_length=16,
                        verbose_name="aaguid data",
                    ),
                ),
                (
                    "credential_id",
                    models.BinaryField(
                        max_length=1023, verbose_name="credential id data"
                    ),
                ),
                (
                    "credential_id_md5",
                    models.BinaryField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="hashed credential id",
                    ),
                ),
                (
                    "cose_public_key",
                    models.BinaryField(
                        max_length=1023, verbose_name="COSE public key data"
                    ),
                ),
                (
                    "transports",
                    models.JSONField(
                        default=list, editable=False, verbose_name="transports"
                    ),
                ),
                (
                    "authenticator_attachment",
                    models.CharField(
                        choices=[
                            ("cross-platform", "cross-platform"),
                            ("platform", "platform"),
                        ],
                        editable=False,
                        max_length=24,
                        verbose_name="authenticator attachment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that this device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey device",
                "verbose_name_plural": "passkey devices",
                "swappable": "OTP_PASSKEYS_MODEL",
            },
        ),
    ]
