version: 2
updates:
  # all NPM packages
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
