# Generated by Django 5.1.3 on 2024-12-01 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_otp_webauthn",
            "0001_squashed_0003_webauthncredential_hash_binary_to_hex",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnUserHandle",
            fields=[
                (
                    "handle_hex",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        unique=True,
                        verbose_name="handle hex",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="webauthn_user_handle",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebAuthn user handle",
                "verbose_name_plural": "WebAuthn user handles",
            },
        ),
    ]
