# Generated by Django 5.1.3 on 2024-12-01 16:18

import hashlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_handle_for_users_with_existing_credentials(apps, schema_editor):
    WebAuthnUserHandle = apps.get_model("django_otp_webauthn", "WebAuthnUserHandle")
    WebAuthnCredential = apps.get_model("django_otp_webauthn", "WebAuthnCredential")

    # For users that already have credentials, create a handle object based on
    # what the user handle must have been at the time of registration. This is
    # important, otherwise browsers will consider the credential to belong to a
    # different user.
    for user_id in WebAuthnCredential.objects.values_list(
        "user_id", flat=True
    ).distinct():
        WebAuthnUserHandle.objects.create(
            user_id=user_id, handle_hex=hashlib.sha256(bytes(user_id)).digest().hex()
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_otp_webauthn",
            "0001_squashed_0003_webauthncredential_hash_binary_to_hex",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthnUserHandle",
            fields=[
                (
                    "handle_hex",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        unique=True,
                        verbose_name="handle hex",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="webauthn_user_handle",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebAuthn user handle",
                "verbose_name_plural": "WebAuthn user handles",
            },
        ),
        migrations.RunPython(
            add_handle_for_users_with_existing_credentials,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
