name: Nightly tests
# Inspired by: https://github.com/torchbox/wagtailmedia/blob/main/.github/workflows/nightly-tests.yml

on:
  schedule:
    # Run every Monday at midnight
    - cron: "0 0 * * 1"

  # Or manually to test
  workflow_dispatch:

jobs:
  nightly-e2e:
    # Cannot check the existence of secrets, so limiting to repository name to prevent all forks to run nightly.
    # See: https://github.com/actions/runner/issues/520
    if: ${{ github.repository == 'Stormbase/django-otp-webauthn' }}
    uses: ./.github/workflows/playwright-tests.yml
  nightly-test:
    # Cannot check the existence of secrets, so limiting to repository name to prevent all forks to run nightly.
    # See: https://github.com/actions/runner/issues/520
    if: ${{ github.repository == 'Stormbase/django-otp-webauthn' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install additional system packages
        run: |
          sudo apt-get update -y
          # Need `gettext` to compile translations
          sudo apt-get install gettext

      - name: Install dependencies
        run: |
          python -m pip install tox requests .[testing]

      - name: Compile translations
        run: |
          /bin/sh ./scripts/compile_translations.sh

      - name: Run 'future' tests
        id: test
        continue-on-error: true
        run: |
          tox -e future

      - name: Send Slack notification on failure
        if: steps.test.outcome == 'failure'
        run: |
          python .github/report_nightly_build_failure.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
