name: Playwright Tests
on:
  workflow_call:
  workflow_dispatch:

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

# Only allow a single run to be active on this branch
concurrency:
  group: "playwright-tests-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  playwright:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          cache: "pip"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
      - uses: gerlero/apt-install@c0fa73fe5c4a22deecf6d629565be92a15dd2026 # v1.3.12
        name: Install gettext
        with:
          packages: gettext
      - name: Install frontend dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Compile JavaScript
        run: |
          yarn build
      - name: Install backend dependencies
        run: |
          python -m pip install .[testing,playwright]
      - name: Compile translations
        run: /bin/sh ./scripts/compile_translations.sh
      - name: Run E2E tests
        run: |
          /bin/sh ./scripts/run_e2e_testsuite.sh
      - name: Upload Playwright traces
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 3
