name: Publish to Test PyPI
on:
  release:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [prereleased]

concurrency:
  group: "publish-test-${{ github.ref }}"
  cancel-in-progress: false # Don't cancel in-progress publish jobs, they may be in the middle of uploading to PyPI!
env:
  PYTHONNOUSERSITE: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

permissions: {}

jobs:
  publish:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to download release artifacts
      id-token: write # Needed for Trusted Publishing to PyPI
    environment:
      name: pypi
      url: https://test.pypi.org/p/django-otp-webauthn/
    steps:
      - name: Download release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          mkdir dist
          gh release download "$TAG" \
          --repo "$GITHUB_REPOSITORY" \
          --dir dist \
          --pattern "*.whl" \
          --pattern "*.tar.gz" \
          --pattern "sha256sums.txt"

      - name: Verify checksums
        run: |
          mv dist/sha256sums.txt sha256sums.txt
          sha256sum --check sha256sums.txt

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
        with:
          packages-dir: ./dist
          repository-url: https://test.pypi.org/legacy/
