name: Check Documentation Spelling

on:
  workflow_run:
    workflows: ["Build Documentation"]
    types:
      - completed
  workflow_dispatch:
  pull_request:
    branches: ["**"]

jobs:
  spelling:
    runs-on: ubuntu-latest
    # Only run if the build-docs workflow succeeded or on PR/manual trigger
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}

    steps:
      - uses: actions/checkout@v4

      - name: Download documentation artifacts
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: django-otp-webauthn-docs
          path: docs/_build/html/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling

      - name: Install Aspell
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-en

      - name: Build Documentation (if not from workflow_run)
        if: github.event_name != 'workflow_run'
        run: |
          pip install -e '.[docs]'
          cd docs && make html

      - name: Spell check
        working-directory: ./docs
        run: |
          python -m pyspelling -c spellingcheck.yaml
